### ISSUE TITLE
Using this API

### ISSUE THREAD

**Issue by LukeJW0** [treetreet0rrm0uth/SchoologyAPI#1]
Hi, is this API working, and if so, how can I use it? I am looking for an easy way to access Schoology's API for a project of mine.

**Comment by treetreet0rrm0uth** [comment]
Hello! Thank you for showing interest in this project! I will soon add instructions on how to use the API.

**Comment by treetreet0rrm0uth** [comment]
Finished! Now you can access the instructions from "readme.md". I would love to take a look at your project once it's finished! Once again, thank you for taking interest in this! :)
